# Generated by Django 2.2.28 on 2022-08-24 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 13, 7, 23, 475224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='btc',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
